### ISSUE TITLE
../peg.go:1265: closure needs too many variables; runtime will reject it

### ISSUE THREAD

**Issue by ziutek** [knieriem/markdown#1] opened 2011-01-30 00:03 UTC
I get this error during make.
I try make pointlander / peg and there is no errors

**Comment by knieriem** [comment] 2011-01-30 01:36
Apparently closure `compile` is using to many variables from the enclosing context. The problem is also [discussed at golang-nuts](http://groups.google.com/group/golang-nuts/browse_thread/thread/b50a2f423d63ef0a).

I wasn't aware of this because I'm using 8g on GOARCH=386, and the error can be observed with 6g – the latter probably can cope with half the number of variables only (i.e. 12). I'll try to reduce the number of variables again.

(BTW, if you just want to use _markdown_, and don't need to modify parser.leg, you won't need to compile _peg_, as there already exists a pre-generated parser.leg.go.)

**Comment by knieriem** [comment] 2011-01-30 22:31
Should be fixed in the latest revision: knieriem/peg@0c7c7374e030d45bf41156c74c794d4786203868

I replaced some closures, which were stored into variables in tree.Compile, by methods of a new type `writer`. This saved a number of variables large enough to make the error vanish.

**Comment by ziutek** [comment] 2011-01-31 12:24
Yes. Now I get no errors.

**Closed as completed** 2011-02-02 22:41 UTC
